### ISSUE TITLE
Dashboard Test Results

### ISSUE THREAD

**Issue by akihitoiwai0912** [xronos-inc/xronos-dashboard#4]
Using simple LF codes, I tested dashboard display while doing zoon in/out. Here are some issues and improvement. Please see the details at each links.

- [Reaction execution time resolution #1](https://github.com/densoGSR/lf_test/issues/1)
- [Displayed for each reaction in the reaction execution view #2](https://github.com/densoGSR/lf_test/issues/2)
- [Zoom in operation error #3](https://github.com/densoGSR/lf_test/issues/3)
- [Change of Logical time tag number after zoom in #4](https://github.com/densoGSR/lf_test/issues/4)

**Comment by elgeeko1** [comment]
@akihitoiwai0912 I have responded to each of the issues.

**Comment by elgeeko1** [comment]
Addressed by https://github.com/xronos-inc/xronos-dashboard/pull/5
